[tool.poetry]
name = "social-energie-prijzen-bot"
version = "0.1.0"
description = "Script voor social media bot"
authors = ["itheo.tech <theo@vandersluijs.nl>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
APScheduler = "^3.9.1.post1"
requests = "^2.28.1"
"Mastodon.py" = "^1.8.0"
tweepy = "^4.12.1"
toml = "^0.10.2"
praw = "^7.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
